version: '3.8'

services:

  #web:
  #  name: "thoughty-web"
  #  restart: unless-stopped
  #  build: .
  #  depends_on:
  #    - db
  #  env_file:
  #    - .env

  db:
    name: "thoughty-db"
    restart: unless-stopped
    image: mongo:latest
    volumes:
      - ./db:/data/db
    env_file:
      - .env
    #ports:
    #  - "5050:27017"

  web_proxy:
    name: "thoughty-web-proxy"
    image: caddy
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy-data:/data
      - ./data/caddy-config:/config